### ISSUE TITLE
Close Thread doesn't work via reply

### ISSUE THREAD

**Issue by Destroy666x** [mybb/mybb#2022]
Close Thread doesn't work via reply/quick reply...

https://github.com/mybb/mybb/blob/featur...#L889-L901

Original thread: [Close Thread doesn't work via reply](http://community.mybb.com/thread-171504.html)

EDIT: also: http://community.mybb.com/thread-171504-post-1161753.html#pid1161753

**Comment by Sama34** [comment]
#1463

**Comment by Cu8eR** [comment]
Is it bugged only in postbit quick reply?

**Comment by thunderclap82** [comment]
Is there a way to manually fix this bug until a proper update comes along? I'm still experiencing it in 1.8.7.

**Comment by Sama34** [comment]
IIRC this was fixed within #1922

**Comment by Cu8eR** [comment]
@Sama34 - this issue is still here :( annoying

**Comment by Sama34** [comment]
What do you mean by "here"? The master branch?

**Comment by Cu8eR** [comment]
At least in MyBB 1.8.7 still bugged

**Comment by thunderclap82** [comment]
That's the version of MyBB I have too. (1.8.7) The bug is still present in my copy.

**Comment by Destroy666x** [comment]
That PR introduced the bug, not fixed it. I'll try to finish the PR ASAP, but feel free to take it over.
